/*******************************************************************************************
* This file has been automatically generated by SmartSAR Configurator
* Smart OSEK v4.5.
*
* PLEASE DO NOT EDIT THIS FILE.
*
* Copyright 2009-2013 by Embedded System and Engineering Center of Zhejiang University (ESE)
* All rights exclusively reserved. Reproduction in whole or in part is    prohibited
* without the prior written consent of the copyright owner. The information presented in this
* document does not form part of any quotation or contract, is believed to be    accurate and
* reliable and may be changed without notice.    No liability will be accepted by the publisher
* for any consequence of its use. Publication thereof does not convey nor imply any license
* under patent or other industrial or intellectual property rights.
*******************************************************************************************/


#include "App_Cfg.h"

/*************************************************************
* user configurations -- TASK
**************************************************************/

#if (OS_TASK_NUM > 0)
    #if ((OS_SC_MODULE==OS_SC2_MODULE ||OS_SC_MODULE==OS_SC4_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON)
           INT32U MaxCrossTime = 0;
    #endif

/*******************************************************************
| Defines all the call back function
|------------------------------------------------------------------*/
    
    OSSTK EcuMStartupTwoTaskStack[EcuMStartupTwoTaskStackSize]__attribute__((aligned(16)));
    TaskType EcuMStartupTwoTask = &OSTCBTbl[1];
    OSSTK OsTask_0Stack[OsTask_0StackSize]__attribute__((aligned(16)));
    TaskType OsTask_0 = &OSTCBTbl[2];
    OSSTK OsTask_1Stack[OsTask_1StackSize]__attribute__((aligned(16)));
    TaskType OsTask_1 = &OSTCBTbl[3];
    OSSTK OsTask_2Stack[OsTask_2StackSize]__attribute__((aligned(16)));
    TaskType OsTask_2 = &OSTCBTbl[4];
    // OSSTK OsTask_3Stack[OsTask_3StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_3 = &OSTCBTbl[5];
    // OSSTK OsTask_4Stack[OsTask_4StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_4 = &OSTCBTbl[6];
    // OSSTK OsTask_5Stack[OsTask_5StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_5 = &OSTCBTbl[7];
    // OSSTK OsTask_6Stack[OsTask_6StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_6 = &OSTCBTbl[8];
    // OSSTK OsTask_7Stack[OsTask_7StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_7 = &OSTCBTbl[9];
    // OSSTK OsTask_8Stack[OsTask_8StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_8 = &OSTCBTbl[10];
    // OSSTK OsTask_9Stack[OsTask_9StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_9 = &OSTCBTbl[11];
    // OSSTK OsTask_10Stack[OsTask_10StackSize]__attribute__((aligned(16)));
    // TaskType OsTask_10 = &OSTCBTbl[12];

/*******************************************************************
| Defines Task Configuration
|------------------------------------------------------------------*/    
    const OsTask OSTaskCfgTbl[] =
    {
        /*{Task entry, High stack addr, Low stack addr, Original Priority, 
           MAX Activation, Schedule, AutoStartOrNOT, EventMask, ResMask, 
           AppMode AutoStart, TaskTimingProtection, OsTaskAccessingApplication} */
            {/* Task EcuMStartupTwoTask */
                FuncEcuMStartupTwoTask, &EcuMStartupTwoTaskStack[EcuMStartupTwoTaskStackSize-2], EcuMStartupTwoTaskStack, EcuMStartupTwoTaskPrio, 
                #if (OS_RESOURCE_MODULE == STD_ON)
                    INVALID_RESOURCE_PRIO,      
                #endif
                EcuMStartupTwoTaskMaxNum,             /*MAX Activation*/
                OsTask_0Schedule,        /*Schedule Policy*/ 
                TRUE,        /*Autostart or not*/
                0,                    /*Events Mask*/
                0,                /*Resource Mask*/
                ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
                    {100, 100, EcuMStartupTwoTaskResourceLock},        /*TaskTimingProtection, not supported now*/
            #endif
            },
            {/* Task OsTask_0 */
                FuncOsTask_0, &OsTask_0Stack[OsTask_0StackSize-2], OsTask_0Stack, OsTask_0Prio, 
                #if (OS_RESOURCE_MODULE == STD_ON)
                    INVALID_RESOURCE_PRIO,      
                #endif
                OsTask_0MaxNum,             /*MAX Activation*/
                OsTask_0Schedule,        /*Schedule Policy*/ 
                TRUE,        /*Autostart or not*/
                0,                    /*Events Mask*/
                0,                /*Resource Mask*/
                ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
                    {100, 100, OsTask_0ResourceLock},        /*TaskTimingProtection, not supported now*/
            #endif
            },
            {/* Task OsTask_1 */
                FuncOsTask_1, &OsTask_1Stack[OsTask_1StackSize-2], OsTask_1Stack, OsTask_1Prio, 
                #if (OS_RESOURCE_MODULE == STD_ON)
                    INVALID_RESOURCE_PRIO,      
                #endif
                OsTask_1MaxNum,             /*MAX Activation*/
                OsTask_1Schedule,        /*Schedule Policy*/ 
                TRUE,        /*Autostart or not*/
                0,                    /*Events Mask*/
                0,                /*Resource Mask*/
                ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
                    {100, 100, OsTask_1ResourceLock},        /*TaskTimingProtection, not supported now*/
            #endif
            },
            {/* Task OsTask_2 */
                FuncOsTask_2, &OsTask_2Stack[OsTask_2StackSize-2], OsTask_2Stack, OsTask_2Prio, 
                #if (OS_RESOURCE_MODULE == STD_ON)
                    INVALID_RESOURCE_PRIO,      
                #endif
                OsTask_2MaxNum,             /*MAX Activation*/
                OsTask_2Schedule,        /*Schedule Policy*/ 
                TRUE,        /*Autostart or not*/
                0,                    /*Events Mask*/
                OsResource_0ID,                /*Resource Mask*/
                ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
                    {100, 100, OsTask_2ResourceLock},        /*TaskTimingProtection, not supported now*/
            #endif
            },
            // {/* Task OsTask_3 */
            //     FuncOsTask_3, &OsTask_3Stack[OsTask_3StackSize-2], OsTask_3Stack, OsTask_3Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_3MaxNum,             /*MAX Activation*/
            //     OsTask_3Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     OsResource_0ID,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_3ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },
            // {/* Task OsTask_4 */
            //     FuncOsTask_4, &OsTask_4Stack[OsTask_4StackSize-2], OsTask_4Stack, OsTask_4Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_4MaxNum,             /*MAX Activation*/
            //     OsTask_4Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     0,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_4ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },
            // {/* Task OsTask_5 */
            //     FuncOsTask_5, &OsTask_5Stack[OsTask_5StackSize-2], OsTask_5Stack, OsTask_5Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_5MaxNum,             /*MAX Activation*/
            //     OsTask_5Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     0,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_5ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },
            // {/* Task OsTask_6 */
            //     FuncOsTask_6, &OsTask_6Stack[OsTask_6StackSize-2], OsTask_6Stack, OsTask_6Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_6MaxNum,             /*MAX Activation*/
            //     OsTask_6Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     0,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_6ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },
            // {/* Task OsTask_6 */
            //     FuncOsTask_7, &OsTask_7Stack[OsTask_7StackSize-2], OsTask_7Stack, OsTask_7Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_7MaxNum,             /*MAX Activation*/
            //     OsTask_7Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     0,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_6ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },
            // {/* Task OsTask_6 */
            //     FuncOsTask_8, &OsTask_8Stack[OsTask_8StackSize-2], OsTask_8Stack, OsTask_8Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_8MaxNum,             /*MAX Activation*/
            //     OsTask_8Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     0,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_6ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },
            // {/* Task OsTask_6 */
            //     FuncOsTask_9, &OsTask_9Stack[OsTask_6StackSize-2], OsTask_9Stack, OsTask_9Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_9MaxNum,             /*MAX Activation*/
            //     OsTask_9Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     0,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_6ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },
            // {/* Task OsTask_6 */
            //     FuncOsTask_10, &OsTask_10Stack[OsTask_10StackSize-2], OsTask_10Stack, OsTask_10Prio, 
            //     #if (OS_RESOURCE_MODULE == STD_ON)
            //         INVALID_RESOURCE_PRIO,      
            //     #endif
            //     OsTask_10MaxNum,             /*MAX Activation*/
            //     OsTask_10Schedule,        /*Schedule Policy*/ 
            //     TRUE,        /*Autostart or not*/
            //     0,                    /*Events Mask*/
            //     0,                /*Resource Mask*/
            //     ( (1<<(OsAppMode_0-1))   ), /*AppMode when task autostart*/
            // #if ((OS_SC2_MODULE == OS_SC_MODULE || OS_SC4_MODULE == OS_SC_MODULE) && OS_TIMING_PROTECTION_MODULE ==  STD_ON) 
            //         {100, 100, OsTask_6ResourceLock},        /*TaskTimingProtection, not supported now*/
            // #endif
            // },

    };
    //#if (OS_SC2_MODULE == OS_SC_MODULE)
            /* the ready list of different priorities */
        uint8 ReadyList1[ReadyList1Length];
        uint8 ReadyList2[ReadyList2Length];
        uint8 ReadyList3[ReadyList3Length];
        uint8 ReadyList4[ReadyList4Length];
        uint8 ReadyList5[ReadyList5Length];
        uint8 ReadyList6[ReadyList6Length];
        uint8 ReadyList7[ReadyList7Length];
        uint8 ReadyList8[ReadyList8Length];
        const ReadyListCfg ReadyListCfgTbl[OS_MAX_TASK_PRIO] = 
        {
             { ReadyList1, ReadyList1Length, }, /* ReadyList1 */
             { ReadyList2, ReadyList2Length, }, /* ReadyList2 */
             { ReadyList3, ReadyList3Length, }, /* ReadyList3 */
             { ReadyList4, ReadyList4Length, }, /* ReadyList4 */
             { ReadyList5, ReadyList5Length, }, /* ReadyList5 */
             { ReadyList6, ReadyList6Length, }, /* ReadyList6 */
             { ReadyList7, ReadyList7Length, }, /* ReadyList7 */
             { ReadyList8, ReadyList8Length, }, /* ReadyList7 */
        };


    //#endif /* OS_SC2_MODULE */
#else
        const ReadyListCfg ReadyListCfgTbl[1] =
        {
        
        };
#endif


/*************************************************************
* user configurations -- EVENT
**************************************************************/
    #if (OS_EVENT_MODULE == STD_ON)
        EventMaskType OsEvent_0 = OsEvent_0Mask;
    #endif /* OS_EVENT_MODULE */
    
    
/*************************************************************
* user configurations -- COUNTER & ALARM
**************************************************************/
#if (OS_ALARM_MODULE == STD_ON && OS_ALARM_NUM > 0)
    


/*******************************************************************
| Defines OsCounter Configuration
|------------------------------------------------------------------*/
    const OsCounter OSCounterCfgTbl[] =
    {/* {Max allowed value,Minimum cycle,Ticks per Base, counter type,Second per ticks} */
        {/* OsCounter_0 */
        OSCOUNTER_0_MAXALLOWEDVALUE,
        OSCOUNTER_0_MINIMUMCYCLE,
        OSCOUNTER_0_TICKSPERBASE, 

        HARDWARE,
        /* Time of one hardware tick in seconds.>> not support now */
        1/OS_TICKS_PER_SEC,
        },
    };

    
/*******************************************************************
| Defines OsAlarmAutostart Configuration
|------------------------------------------------------------------*/
    OsAlarmAutostart OSAlarmAutostartCfgTbl[]=
    /*offset, Abs/Rel Autostart, cycle, Autostart AppMode*/
    {
        {/* OsAlarm_1 */
        10,        /*Alarm Time*/
        RELATIVE,
        10,        /*osAlarmCycleTime")*/
        ((1<<(OsAppMode_0-1)) +  0) /*AppMode when autostart */            
        },
        {/* OsAlarm_2 */
        200,        /*Alarm Time*/
        RELATIVE,
        10,        /*osAlarmCycleTime")*/
        ((1<<(OsAppMode_0-1)) +  0) /*AppMode when autostart */            
        },
        {/* OsAlarm_3 */
        300,        /*Alarm Time*/
        RELATIVE,
        4,        /*osAlarmCycleTime")*/
        ((1<<(OsAppMode_0-1)) +  0) /*AppMode when autostart */            
        },
        {/* OsAlarm_4 */
        20,        /*Alarm Time*/
        RELATIVE,
        5,        /*osAlarmCycleTime")*/
        ((1<<(OsAppMode_0-1)) +  0) /*AppMode when autostart */            
        },
        {/* OsAlarm_5 */
        100,        /*Alarm Time*/
        RELATIVE,
        10,        /*osAlarmCycleTime")*/
        ((1<<(OsAppMode_0-1)) +  0) /*AppMode when autostart */
        },
    };


/*******************************************************************
| Defines Application Alarm Configuration
|------------------------------------------------------------------*/


/*******************************************************************
| Defines OsAlarm Configuration
|------------------------------------------------------------------*/
  OsAlarm OSAlarmCfgTbl[] =
  { /* {CounterID,Alarm Action,} */
    { /* OsAlarm_0*/    
        OsCounter_0, /*CounterRef*/
        /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/          
        {INVALID_COUNTER,
        #if (OS_ALARM_CALLBACK == STD_ON)
        NULL_PTR,
        #endif
        #if (OS_EVENT_MODULE == STD_ON)
        { NULL_PTR, OS_TASK_INVALID },
        #endif
        OsTask_0ID
        },
             &OSAlarmAutostartCfgTbl[0],    /* non-Autostart*/
      },
    // { /* OsAlarm_1*/    
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/          
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_1ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    // { /* OsAlarm_2*/    
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/          
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_2ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    // { /* OsAlarm_3*/    
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/          
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_3ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    // { /* OsAlarm_4*/    
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/          
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_4ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    // { /* OsAlarm_5*/
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_5ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    //   { /* OsAlarm_6*/
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_6ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    //   { /* OsAlarm_7*/
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_7ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    //   { /* OsAlarm_8*/
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_8ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },
    //   { /* OsAlarm_9*/
    //     OsCounter_0, /*CounterRef*/
    //     /*Alarm Action: IncrementCounter, CallBack, SetEvent (EventRef, TaskID), ActiveTask*/
    //     {INVALID_COUNTER,
    //     #if (OS_ALARM_CALLBACK == STD_ON)
    //     NULL_PTR,
    //     #endif
    //     #if (OS_EVENT_MODULE == STD_ON)
    //     { NULL_PTR, OS_TASK_INVALID },
    //     #endif
    //     OsTask_9ID
    //     },
    //         &OSAlarmAutostartCfgTbl[0],
    //   },

  };
 
#endif  /* OS_ALARM_MODULE */
  

    AlarmType OsAlarm_0 = &OSAlarms[0];
    // AlarmType OsAlarm_1 = &OSAlarms[1];
    // AlarmType OsAlarm_2 = &OSAlarms[2];
    // AlarmType OsAlarm_3 = &OSAlarms[3];
    // AlarmType OsAlarm_4 = &OSAlarms[4];
    // AlarmType OsAlarm_5 = &OSAlarms[5];

/*************************************************************
* user configurations -- RESOURCE
**************************************************************/
#if (OS_RESOURCE_MODULE == STD_ON) && ((OS_RES_EXTERNAL == STD_ON) || (OS_RES_INTERRUPT == STD_ON)||OS_RES_INTERNAL == STD_ON)    

    
/*******************************************************************
| Defines Application Resource Configuration
|------------------------------------------------------------------*/
    
/*******************************************************************
| Defines OsResource Configuration
|------------------------------------------------------------------*/
    const OsResource OSResourceCfgTbl[]=
    {
    {/* OsResource_0 */
    STANDARD, 0,OsResource_0Prio
    },
    };

    #if(OS_RES_EXTERNAL == STD_ON ||OS_RES_SCHEDULER == STD_ON)
    ResourceType OsResource_0 = &OSResources[0];
    #endif /* OS_RES_EXTERNAL */


       
#endif /* OS_RESOURCE_MODULE */


/*************************************************************
* user configurations -- INTERRUPT
**************************************************************/

/*************************************************************
* user configurations -- SCHEDULE TABLE
**************************************************************/
  

    
/*************************************************************
* user configurations -- APPLICATION
**************************************************************/
        

