/*******************************************************************************************
* This file has been automatically generated by SmartSAR Configurator
* Smart OSEK v4.5.
*
* PLEASE DO NOT EDIT THIS FILE.
*
* Copyright 2009-2013 by Embedded System and Engineering Center of Zhejiang University (ESE)
* All rights exclusively reserved. Reproduction in whole or in part is    prohibited
* without the prior written consent of the copyright owner. The information presented in this
* document does not form part of any quotation or contract, is believed to be    accurate and
* reliable and may be changed without notice.    No liability will be accepted by the publisher
* for any consequence of its use. Publication thereof does not convey nor imply any license
* under patent or other industrial or intellectual property rights.
*******************************************************************************************/


#include "App_Cfg.h"
#include "Os.h"
#include "aaa_print.h"
//#include "EcuM.h"
//#include "Isr_vector.h"



TASK(EcuMStartupTwoTask)
{
    uint8 i;
    //EcuM_StartupTwo();
    //INTCTblInit();
    for(int i=0;i<50;i++){
        print_char(" ecu task working ...");

    }
    TerminateTask();
}


















